[package]
name = "server-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.74"
futures = "0.3.29"
mongodb = "2.7.1"
tokio = { version = "1.34.0", features = ["macros"] }
warp = "0.3.6"
