[package]
name = "server-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.74"
base64 = "0.22.0"
futures = "0.3.29"
mongodb = "2.8.2"
serde = "1.0.197"
serde_json = "1.0.115"
tokio = { version = "1.34.0", features = ["macros"] }
warp = "0.3.6"
